services:
  web:
    image: lwonsang/cse427s_finalproject-web
    ports:
      - "8090:80"
    env_file:
      - ./NewsSharingApp/.env

  ml:
    image: lwonsang/cse427s_finalproject-ml
    volumes:
      - ./MachineLearning:/app
    ports:
      - "5000:5000"
    command: python app.py