apiVersion: v1
kind: Service
metadata:
  name: textclassifydeploymentservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: textclassify-app
  ports:
    - port: 80
      targetPort: 5000
